repos:
  - repo: local
    hooks:
      - id: ruff
        name: Run ruff
        entry: ruff check --fix --exit-non-zero-on-fix
        language: system
        types: [python]
      - id: ruff-format
        name: Run ruff format
        entry: ruff format
        language: system
        types: [python]
      - id: pytest
        name: Run pytest (Python)
        entry: sh -c 'uv run pytest'
        language: system
        pass_filenames: false
        always_run: true
